version: '3'
networks:
  devVNet:
    driver: bridge
    external: true

services:
  app:
    container_name: 'daprPubSubExample'
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.devContainer
      args:
        # Update 'VARIANT' to pick a version of .NET: 3.1-focal, 5.0-focal, 6.0-focal
        VARIANT: "6.0-focal"
        # Optional version of Node.js
        NODE_VERSION: "none"

    #Opt out of dotnet telemetry gathering
    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT=true
      - ASPNETCORE_ENVIRONMENT=Development

    volumes:
      - ..:/daprPubSubExample:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    networks:
      - devVNet

  sidecar:
    image: daprsidecar:latest
    restart: always
    container_name: "daprPubSubExample-sidecar"

    command: ["-app-id", "daprPubSubExample"]

    network_mode: "service:app"

    depends_on:
      - app